### ISSUE TITLE
Browser tests fail when requiring Authentication

### ISSUE THREAD

**Issue by rwilliams** [mikepb/clerk#5]
Numerous tests fail with a database that requires authentication. I'm not sure if CouchDB likes the xhr auth. I had success converting the auth info into in a Basic Auth header instead of using the xhr user and pass.

**Comment by mikepb** [comment]
The node library replaces the browser XHR implementation with a https://github.com/request/request implementation in `index.js`. I don't think I wrote tests for auth, but I've been able to connect to Cloudant without issues.

How are you providing the auth? The library expects it to be in the URL, i.e. `http://username:password@localhost:5984`.

**Comment by rwilliams** [comment]
I'm providing auth just like that against CouchDB 1.5.0 running locally. My ultimate goal is to use this as a client for Couchbase Lite android so the Auth Header would work nicely there too.

**Comment by mikepb** [comment]
Does Couchbase Lite Android use the NPM module or the browser version? If it uses the browser version, I have definitely never tested auth with XHR. Maybe #6 would be good long-term solution for this?

**Comment by rwilliams** [comment]
Couchbase Lite will use the browser version. It would definitely be nice to unify the code base.

**Comment by mikepb** [comment]
I've updated clerk to use superagent. Could you try it out?

The updates have not been published to npm yet, giving it a bit of time on GitHub to find bugs.

**Comment by rwilliams** [comment]
I can't get auth to work at all now. I try adding it inline to the url in shared.js. Am i supposed to add it as on options object or something?

**Comment by mikepb** [comment]
It looks like CouchDB doesn't accept the `Authentication` header by default. I've added instructions to `README.md` on how to do that.

CouchDB has been returning a lot of errors during testing. Have you experienced this too?

**Comment by mikepb** [comment]
See also this CouchDB issue:
https://issues.apache.org/jira/browse/COUCHDB-2027?jql=project%20%3D%20COUCHDB%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened%2C%20Resolved%2C%20Closed)%20AND%20text%20~%20%22cors%22

As of writing, the `Authentication` header has not been added to the CORS handler:
https://github.com/apache/couchdb-couch/blob/master/src/couch_httpd_cors.erl

**Comment by rwilliams** [comment]
I'm getting sporadic timeouts when browser testing. I've had all tests pass but the db test because the comparison for the db address in the test is hard coded.

**Comment by mikepb** [comment]
I updated the tests to support different hosts and database names.
